services:
  sql:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=secret1
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=secret2
    ports: 
      - "33060:3306"



